twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@PixelOpenCloudflareTurnstile/fields.html.twig'
    globals:
        telegram_bot_username: '%app.telegram_bot_username%'
        site_base_url: '%app.site_base_url%'

when@test:
    twig:
        strict_variables: true
