controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_core_controllers:
    resource: ../vendor/nevinny/admin-core/src/Controller/
    type: attribute
